name: cw
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - pyproj
  - slycot
  - control
  - numba>=0.46.0
  - pip:
      - numpy-quaternion
      - pyserial-asyncio
      - msgpack
      - msgpack_numpy
      - PyYAML
      - python-dateutil
      - cerberus
      - pyserial
      - tqdm
      - openpyxl
      - psutil
      - requests
      - matplotlib
      - pandas
      - xarray
      - sympy